In [17]:
#!pip install openpyxl

import pandas as pd

In [18]:
finance_report = pd.read_excel('finance-report-042024.xlsx', sheet_name='Transaction Journal', skiprows=2, index_col=0)
finance_report.head()

,PR/HR No.,Report No.,Category (optional),Transaction Reference,Transaction Date,Reporting Month,Description,2nd Description (Recipent),Activity Code,Budget Line Code,...,Total Amount In USD,Charging%,InforEuro Rate USD to EUR,Net / Reporting Amount,Payment Status,Invoice Date,Transactions per day,Average Total Amount In USD,Relative deviation,Velocity Score
1,B 00240,1st Report,HR Field,1.0,2024-02-29,yyyy02,February Salary-24 - Person A - Dialysis Techn...,Person A,1.0,1.1.1,...,400.00,1.0,0.922,368.80000,Bank Payment,NaT,3,392.592222,0.018869,1.405163
2,B 00240,1st Report,HR Field,2.0,2024-02-29,yyyy02,Transfer fees for February Salary-24 - Person...,PTT,4.0,4.10.,...,4.00,1.0,0.922,3.68800,Bank Payment,NaT,14,5.557669,0.280274,2.988324
3,B 03763,1st Report,HR Field,3.0,2024-02-29,yyyy02,February Salary-24 - Huseın Ahmad Jabran- Dial...,Huseın Ahmad Jabran,1.0,1.1.1,...,400.00,1.0,0.922,368.80000,Bank Payment,NaT,3,392.592222,0.018869,1.405163
4,B 03763,1st Report,HR Field,4.0,2024-02-29,yyyy02,Transfer fees for February Salary-24 - Huseın ...,PTT,4.0,4.10.,...,4.00,1.0,0.922,3.68800,Bank Payment,NaT,14,5.557669,0.280274,2.988324
5,B 00304,1st Report,HR Field,5.0,2024-02-29,yyyy02,February Salary-24 -Husam Aldin Nader Al Shawi...,Husam Aldin Nader Al Shawi,1.0,1.1.1,...,333.33,1.0,0.922,307.33026,Bank Payment,NaT,3,392.592222,0.150951,1.537245

In [22]:
solidarity_syria = pd.read_excel('Updated_SENED_Budget_Solidarity_Syria-Turkey_2023_05_17_EN.xlsx', sheet_name='Transactions List', skiprows=3, index_col=0)
solidarity_syria.head()

,Budget,REF,no. of vouch-er,Internal voucher number of the\nRecipient,Date of \nvoucher,Name of the Recipient\nfrom voucher/evidence,Reason for payment\n(detailled content of voucher/evidence),Currency \nof voucher,Amount \nof voucher\n,Exchange rate\n(according EU currency converter or exchange of funds),Expenditure in the currency of Grant Agreement\n\n€,Unnamed: 12,Year,Period,Unnamed: 15
No,,,,,,,,,,,,,,,
1.0,1.1.08,S2400800388,F09683,Social Security,2024-08-31 00:00:00,MOHAMMAD YASSER MALATI,MOHAMMAD YASSER MALATI/ Social Security Augu...,TRY,13363.84,0.02792,373.118413,NaN,2024.0,8.0,0.0
2.0,1.1.08,S2400800388,F09696,Income Tax & Stamp,2024-08-31 00:00:00,MOHAMMAD YASSER MALATI,MOHAMMAD YASSER MALATI/ Income Tax & Stamp T...,TRY,4149.53,0.02792,115.854878,NaN,2024.0,8.0,0.0
3.0,1.1.08,S2400800388,F09216,Salary,2024-08-31 00:00:00,MOHAMMAD YASSER MALATI,MOHAMMAD YASSER MALATI/ Bank Paid Net Salary...,TRY,24113.53,0.02792,673.249758,NaN,2024.0,8.0,1.0
4.0,1.1.08,S2400900388,F07182,Social Security,2024-09-30 00:00:00,MOHAMMAD YASSER MALATI,MOHAMMAD YASSER MALATI/ Social Security Sept...,TRY,13466.64,0.02646,356.327294,NaN,2024.0,9.0,0.0
5.0,1.1.08,S2400900388,F08575,Salary,2024-09-30 00:00:00,MOHAMMAD YASSER MALATI,MOHAMMAD YASSER MALATI/ Bank Paid Net Salary...,TRY,32702.31,0.02646,865.303123,NaN,2024.0,9.0,0.0